### ISSUE TITLE
[**PRIORITY**] Automatically inject resaga Reducer and Saga

### ISSUE THREAD

**Issue by quandhz** [quandhz/resaga#20]
Users only need to setup `injectReducer` and `injectSagas` once, then they wouldn't need to manually inject resaga `reducer and saga` anymore.

```
// ReactBoilerPlate example
// app.js
const store = configureStore();
// call this to setup resaga injectors
resaga.setInjectors(getAsyncInjectors(store));
```
Then there is no need to import `reducer and sagas` anymore

**Before**
```
getComponent={(nextState, cb) => {
  const importModules = Promise.all([
    import('resaga'),
    import('containers/BookPage'),
  ]);
  const renderRoute = loadModule(cb);
  importModules.then(([resaga, component]) => {
    injectReducer('BookPage', resaga.reducer('BookPage'));
    injectSagas(resaga.sagas);
    renderRoute(component);
  });
  importModules.catch(errorLoading);
}}
```
**After**
```
getComponent={(nextState, cb) => {
  import('containers/BookPage')
    .then(loadModule(cb))
    .catch(errorLoading);
}}
```

**Comment by QuanDhz** [comment]
Prevent breaking change: Should throw Error if both `injectors` is set and `resaga.reducer` is called. (reducer and saga will be injected twice)

**Comment by QuanDhz** [comment]
This might not be practical due to scope issue. Users might want to import reducer and saga to parent, not the self-contained component itself.
Need some more thoughts on this.

**Comment by quandhz** [comment]
Now we abandon the idea of wrapping self-contained component with resaga. This auto inject feature should not be a problem anymore.
