### ISSUE TITLE
Performance first, support Normalised State using getter

### ISSUE THREAD

**Issue by quandhz** [quandhz/resaga#57]
Say we have a `BookList` component that renders a list of books.
The `BookList` will map through `bookIds` array, give each `BookItem` a `bookId` prop.

Then each `BookItem` would only subscribe to the related array element, and prevent unnecessary re-renders.

Pseudo-code:
```
// Redux Store - BookPage:
- bookIds: [1, 2, 4]
- books: [
  { id: 1, name: 'Data Com' },
  { id: 2, name: 'HTML 101' },
  { id: 3, name: 'Java 101' },
]

// BookList config
export const CONFIG = {
  value: {
    allBooks: ['BookPage', 'bookIds'],
  },
};

// BookItem config
export const CONFIG = {
  value: {
    book: {
      keyPath: ['BookPage', 'books'],
      getter: (books, props) => find(books, { id: props.bookId }),
    },
  },
};
```
This way, `BookList` will not be re-render if some book's content has been updated. It only reconciles when the array length has been changed, and vice versa for `BookItem`.

**Comment by paulcedrick** [comment]
This might help for this one -> https://github.com/paularmstrong/normalizr

**Comment by quandhz** [comment]
That library is indeed where I got this idea from.

**Comment by quandhz** [comment]
But normalised state is about how we want to store the value in React.
`resaga` just gave you the tools you need.

**Comment by paulcedrick** [comment]
I see, so if in case I fetch some stuff, should I manually normalize the state first? or will `resaga` do the work of normalizing it?

**Comment by quandhz** [comment]
`resaga` will do the jobs of setting (subscribing) values and mapping those values to our component's props.

Our job is telling `resaga` how to fetch data (`requests`), and how to normalise the result server responded (`processResult` might be a good place to start with)

Pseudo-code:
```
const CONFIG = {
  processResult: { // pre-process server response before returning to component
    fetchTab: (tabData) =>
      normalize(tabData, [schema.tab]),
  },
  requests: {
    fetchTab: (id) =>
      requests.fetchWithAuthorisation('get', `/templatetabs/${id}`),
  },
};
```

Ideally, our component would only work with normalised data.

**Comment by paulcedrick** [comment]
Nice! That would be awesome added feature for this one. :+1:

**Comment by quandhz** [comment]
Interesting isn't it?
I'll spend some time this sprint on refactoring our TemplateManagement using normalised (and immutable) data. That'd be much clearer and easier to manipulate the data locally as well as optimise performance.

**Comment by paulcedrick** [comment]
Yup! It's something I'm looking forward as well which thankfully landing as feature in resaga.

Will look forward to that refactor and learn from it how I can use the new feature as well :+1:

**Comment by quandhz** [comment]
Stay tuned :happy_bert:
